baseurl: /blog
permalink: /:year/:month/:day/:title.html   #博文的固定链接
author:                                     #自定义常量
name: Eric
email: txl263@163.com
link: http://txl263.github.io/blog/
locals:                                     #自定义常量
tags: 标签
about: 关于
active: 技术
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: redcarpet                         #markdown解释器